### ISSUE TITLE
[FEATURE REQUEST] Raw Input Buffer

### ISSUE THREAD

**Issue by TheBarii** [flarialmc/dll#112]
### Feature description

This module / feature can take mouse input data directly from the Windows API and feed it into Minecraft.

### Reason

While I'm not sure if it proves to be of any real use as Minecraft may as well already use this method to get input data, it may decrease input latency if it does not.

### Additional context

Currently in a client named Central Client.

**Comment by PoopyHaters** [comment]
Didn't @treegfx add this

**Comment by treegfx** [comment]
yes

**Comment by treegfx** [comment]
it exists in the game already tho
