### ISSUE TITLE
[FEATURE REQUEST] proximity chat

### ISSUE THREAD

**Issue by Suppexe** [flarialmc/dll#142]
### Feature description

like the java mod proximity chat

### Reason

i think its gonna be funny when playing skywars with friends 
(kinda silly and specific reason but i like to scream when i die or fell in the void in skywars so if i play with my friend and scream when i fell into the void,the scream will slowly fade out

### Use case

playing with friends and even content creations

**Comment by aShanki** [comment]
This will not be implemented, as it is too far out of scope for the Flarial project, we may possibly make something similar *outside* of Flarial Client, however it will not be soon. Thank you for the suggestion!

**Comment by treegfx** [comment]
yes, a thing like this exists already afaik
