### ISSUE TITLE
[Scripting BUG] 

### ISSUE THREAD

**Issue by PoopyHaters** [flarialmc/dll#147]
### Checklist

- [X] I have checked the [FAQ](https://ptb.discord.com/channels/1049946152092586054/1135112998453788672)

- [X] I have searched the [issues](https://github.com/flarialmc/dll/issues?q=is%3Aissue+is%3Aopen) of this repository and believe that this is not a duplicate

### Bug description

Use the script examples

### Expected behavior

Normal text

### Actual behavior

I saw some random things like header (code)

### Steps to reproduce

Scripting - Settings example - use it

### Operating System

Windows 11

### OS Version

newest

### Additional notes

![image](https://github.com/user-attachments/assets/fe535b78-ffb4-4591-b2cc-7b6a7331b85d)

**Comment by PoopyHaters** [comment]
Too buggy 😭

**Comment by TTF-fog** [comment]
https://github.com/flarialmc/scripting-wiki/issues
post this here

**Comment by Withors** [comment]
bud this is not a bud this is example code 
![image](https://github.com/user-attachments/assets/c7c20149-3979-4ad7-9cef-ab9a7b24c884)
