### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by NomadWanderer** [flarialmc/dll#155]
### Feature description

add java inventory keybinds. things like shift-doubleclicking and moving items by pressing the keybind. 

### Reason

quality of life mainly. it would be really nice to move items quickly, and mobile players can move items like this.

### Use case

in bedwars  i guess to move block to my block slot better. its quality of life i would use it anywhere

**Comment by treegfx** [comment]
this is work in progress already.
