### ISSUE TITLE
[FEATURE REQUEST] Disable mods on specific servers that are against server rules (from Cubecraft, Hive, etc.)

### ISSUE THREAD

**Issue by TBroz15** [flarialmc/dll#164]
### Feature description

**This feature limits and disables mods/modules (by the means of can not be enabled back) depending on which server is the player on according to their rules.**

_This feature was implemented by other clients like Onix does._

### Reason

**This feature is for the sake of safety and to make sure that this client is more legal for servers even though it is not designed for hacks.**

In Cubecraft, Freelook and Nick are mods that are not allowed that Flarial has.

![image](https://github.com/user-attachments/assets/e65d2d15-ffa9-4fbe-b4bd-8dfcfd51a73b)
![image](https://github.com/user-attachments/assets/ce858a34-24f1-49d7-b339-58396fd29c81)

In Hive, Freelook is also banned and no hurt cam too.

![image](https://github.com/user-attachments/assets/2e6d59ef-0b8b-4da6-bb2a-0e013489da91)

In case players who use these disallowed modules, Flarial must check if any of the module is legal in the server or not, if not then don't use it. 

### Use case

Well... When this feature is applied, it will make you unlikely to not get banned, get our appeals denied in-case of a false ban, or make misinformation!

### Alternatives

no alternatives at all...

### Additional context

To make things more flexible to add disallowed modules to be disabled on servers instead of hard coding it into some C#, We must create a separate JSON file that list all of the banned modules on specific servers.

This is an example of what should look like:
```json
{
    "*.cubecraft.net": [
        "freelook",
        "nicked"
    ],
    "*.hivebedrock.network": [
        "freelook",
        "no_hurt_cam"
    ],
    "subdomain.domain.topdomain": [
        "illegal_module",
        "another_illegal_module",
        "dookie_module"
    ]
}
```

Take note that in subdomains has a asterisk wildcard, it should work the same way as how globbing works. Such as in `*.cubecraft.net`, no matter what subdomain it is, those modules are disabled as long as the main domain name is the same.

Also Cubecraft declared this client to be legal-ish since players who use Flarial in their reports will be denied by moderators and admins.

**Comment by Withors** [comment]
already a thing but not in json

**Comment by TBroz15** [comment]
Just realized that Freelook and Freecams are different and I forgot its a thing bruhhhhhhhhh

But i could suggest to have it on JSON

**Comment by Aetopia** [comment]
> Just realized that Freelook and Freecams are different and I forgot its a thing bruhhhhhhhhh
> 
> But i could suggest to have it on JSON

Hardcoding module blocks into the client ensures:

- Module availability is controlled by the developers.

- Prevents user tampering, essentially allowing players to use banned modules.

Thus, allowing for server compliance.

As for your suggestion, it could be slightly refactored:

- Instead of a **local** file, prefer a **remote** file. This promotes greater maintainability since all of the metadata is obtained remotely.

- To prevent user tampering, this metadata could be hosted on Flarial's Web API.

- Any forks & the public source code of Flarial Client will not have access to this metadata since Flarial's Web API is supposed to be private.
