### ISSUE TITLE
im getting more aids every time i open flarial

### ISSUE THREAD

**Issue by alteik** [flarialmc/dll#176]
### Checklist

- [X] I have checked the [FAQ](https://ptb.discord.com/channels/1049946152092586054/1135112998453788672)

- [X] I have searched the [issues](https://github.com/flarialmc/dll/issues?q=is%3Aissue+is%3Aopen) of this repository and believe that this is not a duplicate

### Operating System

None

**Comment by TTF-fog** [comment]
it dosen't take a genius to know how to make an issue
