### ISSUE TITLE
[FEATURE REQUEST] Waypoints

### ISSUE THREAD

**Issue by BLS01** [flarialmc/dll#177]
### Feature description

I would like to see waypoints on Flarial Client.
Automatic Waypoints or Manual Waypoints.
Automatic Waypoints Example: In Lunar Client 1.8 When you go to HCF Servers, Lunar Client will automatically make waypoints like:
Focus, HQ, Spawn, Koth and all of that (and yeah i mostly want this because i play hcf l0l)
Manual Waypoints Example:
Keybind Key that opens a little tab on the center where you write down the waypoints name and then press enter to save it (this is based on your current location, kind of obvious tho)

**Comment by Withors** [comment]
фдкуфвн шт
