### ISSUE TITLE
[FEATURE REQUEST] Something dumb but makes it cooler 

### ISSUE THREAD

**Issue by PoopyHaters** [flarialmc/dll#182]
### Feature description

First to tell i have NO IDEA on what im talking about but
Flarial is an mod and i think it would be cooler if we had the FIRST CLIENT instead of the Mod
If it was a client we could call scripting MODS cause its adding on to the client which is also flarial it just adds C++ code to client (idk what im talking bout) and if this was a client it also would take less time to inject & stuff and we would have an better debugger thanks to the devs having access to the source of game (i still dont know a single stuff about what im talking about)

### Reason

cool 😎 

### Use case

call fuealrail a client instead of a mod 💀 

### Alternatives

no

### Additional context

mak clien :D

**Comment by PoopyHaters** [comment]
yes idk what im talking about 😭

**Comment by PoopyHaters** [comment]
dont tell me that its so dumb cause idk what im even saying

**Comment by marioCST** [comment]
I highly recommend not flooding GitHub with bullshit

**Comment by Beavermon** [comment]
holy dumbass

**Comment by treegfx** [comment]
what the fuck 💀💀💀
