### ISSUE TITLE
[BUG] 3 WEEKS WITHOUT A COMMIT 

### ISSUE THREAD

**Issue by PoopyHaters** [flarialmc/dll#185]
### Checklist

- [X] I have checked the [FAQ](https://ptb.discord.com/channels/1049946152092586054/1135112998453788672)

- [X] I have searched the [issues](https://github.com/flarialmc/dll/issues?q=is%3Aissue+is%3Aopen) of this repository and believe that this is not a duplicate

### Bug description

I was trying to see a commit but there wasnt any

### Expected behavior

I expected a commit

### Actual behavior

Instead it was the same one from 3 weeks ago.

### Steps to reproduce

1. Go to github.com/flarialmc/dll 2. Click on commits

### Operating System

Windows 10

### OS Version

newest win 10

### Additional notes

![image](https://github.com/user-attachments/assets/8caed7b4-2748-4014-b56c-574179c53a7b)

**Comment by PoopyHaters** [comment]
also scriptihg branch got .50 so uh add that

**Comment by EpiclyRaspberry** [comment]
bullshit commit
