### ISSUE TITLE
Improvements to Flarial's V-Sync off implementation.

### ISSUE THREAD

**Issue by Aetopia** [flarialmc/dll#22]
**Is your feature request related to a problem? Please describe.**

Flarial disables V-Sync by calling:

```cpp
IDXGISwapChain::Present(0, DXGI_PRESENT_DO_NOT_WAIT)
```

[`DXGI_PRESENT_DO_NOT_WAIT`](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-present) tells the runtime to not wait for a requested frame to be drawn fully.
This flag is meant to be used in [waitable swapchains](https://learn.microsoft.com/en-us/windows/uwp/gaming/reduce-latency-with-dxgi-1-3-swap-chains).

![image0](https://github.com/user-attachments/assets/c26bea90-3e51-42e0-af36-b3d14d8639fd)

Here, `IDXGISwapChain::Present(0, DXGI_PRESENT_DO_NOT_WAIT)` is being used.

The game is reporting an uncapped framerate but [PresentMon](https://github.com/GameTechDev/PresentMon) is reporting different results.

**Describe the solution you'd like**

To properly disable V-Sync, an application must use `DXGI_PRESENT_ALLOW_TEARING` & `DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING` wherever relevant.

For the implementation:

- Hook `IDXGISwapchain::Present`, `IDXGISwapchain::ResizeBuffers` & `IDXGIFactory2::CreateSwapChainForCoreWindow`.

- Call `IDXGISwapchain::Present` with `DXGI_PRESENT_ALLOW_TEARING`.

- Use `DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING` in `IDXGISwapchain::ResizeBuffers` & `IDXGIFactory2::CreateSwapChainForCoreWindow` to support screen tearing.

> [!NOTE]
> - `DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING` can only be added during swapchain creation.
> - If required, the game can be forced to re-create its swapchain by having `IDXGISwapChain::Present` return  [`DXGI_ERROR_DEVICE_RESET`](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-error).
> - Use a variable to check if the hooked `IDXGIFactory2::CreateSwapChainForCoreWindow` method is being called at least once, allowing the client to determine if the swapchain needs to re-created or not.

![image0](https://github.com/user-attachments/assets/4509651c-9d98-47b6-a17a-bfeb23cc7390)

With all of these proposed changes, this is the result.

**Comment by PoopyHaters** [comment]
im gon try to mak this

**Comment by PoopyHaters** [comment]
nvm im too dumb
