### ISSUE TITLE
Custom crosshair editor

### ISSUE THREAD

**Issue by adampiayz** [flarialmc/dll#39]
### Feature description

A custom crosshair editor where you can draw the crosshair you want (like onix), setting presets and maybe even flarial to have some mainstream crosshairs to select from the get go.

### Reason

```Markdown
Some packs have crosshairs we don't like and getting an overlay isn't 100% fullproof since it might not be the exact crossahir you want or there might not even be an overlay. Overall it just makes it less of a pain in the ass lmao
```

### Use case

```Markdown
Amogus crosshair (real)
```

**Comment by PoopyHaters** [comment]
Dont mind my username its auto generated i think but i also want this

**Comment by TheBarii** [comment]
@adampiayz We have not made an editor, use a texturepack for that, but we did make a Custom Crosshair module which lets you change the color of the crosshair on the fly with multiple customization options.
