### ISSUE TITLE
Item Physics Mod Should Be Added to Flarial Client 

### ISSUE THREAD

**Issue by xRealAntman** [flarialmc/dll#42]
### Feature description

Item Physics is a mod which helps in reducing lag especially when you system is low end basically what is does is when you drop a item or a item is droped it is places flat on ground with no animation it reduces lag very much 

### Reason

```Markdown
this should be added to make the game smooth especially when you are playing bedwars or other mini games which requires FPS
```

**Comment by DankDX** [comment]
I already made this #24

**Comment by aShanki** [comment]
Closing due to this being a duplicate of #24
