### ISSUE TITLE
[FEATURE REQUEST] Autoqueue Avoid Maps update

### ISSUE THREAD

**Issue by thendeiser** [flarialmc/dll#56]
### Feature description

So basically i would like the avoid maps thing in the autoqueue module to also requeue if all the maps you could vote for are all in the avoid maps list without having to wait until a map wins as all of the ones that could win are in the list

### Reason

```Markdown
i think this feature should be added because the whole point of autoqueue is to let the client queue for you without having to manually queue which you would do anyways if all the maps you could vote for are maps that you typed in the avoid maps list
```

**Comment by FreezeEngine** [comment]
Implemented by @St0neHunter
