### ISSUE TITLE
[FEATURE REQUEST]  some feature suggestions 

### ISSUE THREAD

**Issue by BentCrow1632** [flarialmc/dll#79]
### Feature description

1. Resize/Move UI elements (Scoreboard, Chat, etc)
2. Waypoints
3. Quickmine/Fastmine
4. Custom Render Distance (make the render distance lower than minecraft normally allows)
5. Show Potion Effects' Duration 

The 3rd suggestion makes you mine faster legitimately by individually holding down left click on each block as opposed to only holding down left click, which mines slower. Demonstrated in this yt video at 14:58 - **https://youtu.be/rvsmv3bo8ps?t=14m58s** 

### Reason

1st suggestion- helps change the scale or move unwanted gui elements from the screen
2nd suggestion- helps trappers, makes it easier to find out where you came from or where your base is and more
3rd suggestion- helps mine blocks more efficiently, can be done in vanilla mc
4th suggestion- helps run the game better on bad PCs
5th suggestion- shows the duration of potion effects without the need to expand the effects menu

**Comment by Aetopia** [comment]
What does quickmine/fastmine do?

**Comment by arsfr** [comment]
> What does quickmine/fastmine do?

I guess it speeds up the animation speed, but not sure either.

**Comment by xStormyy** [comment]
> What does quickmine/fastmine do?

From my understanding, fastmine would simulate the player holding on on an individual block. According to the evident video, if you hold down on individual blocks instead of holding down in general, you'd mine faster

**Comment by Aetopia** [comment]
> > What does quickmine/fastmine do?
> 
> From my understanding, fastmine would simulate the player holding on on an individual block. According to the evident video, if you hold down on individual blocks instead of holding down in general, you'd mine faster

Wouldn't that be somewhat of a macro?

**Comment by xStormyy** [comment]
> > > What does quickmine/fastmine do?
> > 
> > 
> > From my understanding, fastmine would simulate the player holding on on an individual block. According to the evident video, if you hold down on individual blocks instead of holding down in general, you'd mine faster
> 
> Wouldn't that be somewhat of a macro?

Probably, yeah

**Comment by parrot-m** [comment]
3rd feature would be impossible as it is in a way a cheat and can be used as an advantage against other players in a lot of gamemodes that require you to mine fast like for example competitive bridge.

**Comment by parrot-m** [comment]
> 3rd feature would be impossible as it is in a way a cheat and can be used as an advantage against other players in a lot of gamemodes that require you to mine fast like for example competitive bridge.

@BentCrow1632

**Comment by aShanki** [comment]
Please separate this into separate feature request issues for organization purposes
